regex-stmt = <#"\s*"> regex <#"\s*"> stmt-trmntr

reserved-symbols = (
  "!" |
  "\"" |
  "#" |
  "$" |
  "%" |
  "&" |
  "(" |
  ")" |
  "*" |
  "+" |
  "," |
  "-" |
  "." |
  "/" |
  "0" |
  ":" |
  ";" |
  "<" |
  ">" |
  "?" |
  "[" |
  "\\" |
  "]" |
  "^" |
  "_" |
  "`" |
  "{" |
  "|" |
  "}" |
  "~" |
  "¬" |
  "¹" |
  "×" |
  "Σ" |
  "ε" |
  "⁻" |
  "₁" |
  "₂" |
  "→" |
  "↔" |
  "∀" |
  "∃" |
  "∅" |
  "∈" |
  "∘" |
  "∥" |
  "∧" |
  "∨" |
  "∩" |
  "∪" |
  "≤" |
  "≥" |
  "≺" |
  "≻" )

<reserved-symbol-re> = #"[!\"#$%&()*+,-./0:;<>?\[\\\]^_`{|}~¬¹×Σε⁻₁₂→↔∀∃∅∈∘∥∧∨∩∪≤≥≺≻]"
<non-reserved-symbol-re> = #"[^!\"#$%&()*+,-./0:;<>?\[\\\]^_`{|}~¬¹×Σε⁻₁₂→↔∀∃∅∈∘∥∧∨∩∪≤≥≺≻ ]"
<escaped-reserved-symbol-re> = <"%"> #"[!\"#$%&()*+,-./0:;<>?\[\\\]^_`{|}~¬¹×Σε⁻₁₂→↔∀∃∅∈∘∥∧∨∩∪≤≥≺≻]"

regex-cmd = "regex"

(* union-operator = "|" *)
union-operator = #"[\|∪]"

concatenation-operator = " "

(* intersection-operator = "&" *)
intersection-operator = #"[&∩]"

(* complement-operator = "~" *)
complement-operator = #"[~¬]"

other-complement = "\\"

word-edge = ".#."

kleene-star = "*"
kleene-plus = "+"
wildcard = "?"
identity-symbol = "@"

escape-quote = "\""
escape-prefix = "%"

<cross-product> = <":">
composition = ".o."
rewrite = "->"
<nil-symbol> = "0"

<left-grouping-bracket> = <"[">
<right-grouping-bracket> = <"]">

left-optional-bracket = "("
right-optional-bracket = ")"

atomic-symbol = <"\""> #"." <"\""> | non-reserved-symbol-re | escaped-reserved-symbol-re | <"\""> #"." <"\"">
(* atomic-symbol = non-reserved-symbol-re | escaped-reserved-symbol-re *)
(* multi-char-symbol = (non-reserved-symbol-re | escaped-reserved-symbol-re) (non-reserved-symbol-re | escaped-reserved-symbol-re)+ *)

multi-char-symbol = (
  (((<"\""> #"." <"\"">) | non-reserved-symbol-re | escaped-reserved-symbol-re)
   ((<"\""> #"." <"\"">) | non-reserved-symbol-re | escaped-reserved-symbol-re)+) |
  (<"\""> #"." #"."+ <"\"">))

symbol = (
    multi-char-symbol |
    atomic-symbol |
    nil-symbol |
    wildcard |
    identity-symbol
)

<any-space> = <#"\s*">
concatenation = regex <concatenation-operator> regex
union = regex <#"\s*"> <union-operator> <#"\s*"> regex
intersection = regex <#"\s*"> <intersection-operator> <#"\s*"> regex
complement = <complement-operator> <#"\s*"> regex
<grouping> = left-grouping-bracket any-space regex any-space right-grouping-bracket
mapping = symbol |
          symbol cross-product symbol |
          grouping cross-product grouping |
          regex cross-product regex
kleene-star-repetition = regex <kleene-star>
kleene-plus-repetition = regex <kleene-plus>

<regex> = symbol |
        grouping |
        concatenation |
        union |
        complement |
        intersection |
        kleene-star-repetition |
        kleene-plus-repetition |
        mapping

stmt-trmntr = ";"
